CREATE TABLE [dbo].[RoleResources] (
    Id BIGINT IDENTITY(1,1) PRIMARY KEY,
    RoleId NVARCHAR(450) NOT NULL, 
    ResourceId BIGINT NOT NULL,
    FOREIGN KEY (RoleId) REFERENCES AspNetRoles(Id) ON DELETE CASCADE,
    FOREIGN KEY (ResourceId) REFERENCES Resources(Id) ON DELETE CASCADE
);